name: Deploy Frontend

on:
  push:
    branches:
      - main  # Cambia a 'deploy' si esa es tu rama de producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH client with Bastion
        env:
          BASTION_KEY: ${{ secrets.BASTION_KEY }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$BASTION_KEY" > ~/.ssh/bastion.pem
          echo "$SERVER_KEY" > ~/.ssh/server.pem
          chmod 600 ~/.ssh/bastion.pem ~/.ssh/server.pem
          cat <<EOF > ~/.ssh/config
          Host bastion-host
            HostName ${{ secrets.BASTION_HOST }}
            User ${{ secrets.BASTION_USER }}
            IdentityFile ~/.ssh/bastion.pem
            StrictHostKeyChecking no

          Host private-server
            HostName ${{ secrets.SERVER_HOST }}
            User ${{ secrets.SERVER_USER }}
            IdentityFile ~/.ssh/server.pem
            ProxyJump bastion-host
            StrictHostKeyChecking no
          EOF

      - name: Install Git on Private Server
        run: |
          # Se ejecuta de forma independiente para asegurar que dnf eche a andar con sudo sin romper el flujo posterior
          ssh private-server "sudo dnf update -y && sudo dnf install git -y"

      - name: Deploy on server
        run: |
          ssh private-server "
            mkdir -p /home/ec2-user/app-frontend &&
            cd /home/ec2-user/app-frontend &&
            
            if [ ! -d .git ]; then
              git init &&
              git remote add origin https://github.com/VicenteParada/Front_Eval2.git &&
              git fetch origin main &&
              git checkout -f main &&
              git branch --set-upstream-to=origin/main main
            else
              git pull origin main
            fi &&
            
            # Escribir el archivo .env con las variables de producción
            echo 'PORT=${{ secrets.PORT }}' > .env &&
            echo 'DEBUG=False' >> .env &&
            echo 'BACKEND_URL=${{ secrets.BACKEND_URL }}' >> .env &&
            echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env &&
            
            # Ciclo de actualización del contenedor Docker
            docker stop front-app || true &&
            docker rm front-app || true &&
            docker build -t front-eval-image:latest . &&
            docker run -d \
              --name front-app \
              -p ${{ secrets.PORT }}:5000 \
              --env-file .env \
              --restart always \
              front-eval-image:latest
          "
